// <auto-generated/>
namespace DataMapper.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class BorrowBookEdition : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.BorrowedBooksBooks", "BorrowedBooks_Id", "dbo.BorrowedBooks");
            DropForeignKey("dbo.BorrowedBooksBooks", "Book_Id", "dbo.Books");
            DropIndex("dbo.BorrowedBooksBooks", new[] { "BorrowedBooks_Id" });
            DropIndex("dbo.BorrowedBooksBooks", new[] { "Book_Id" });
            CreateTable(
                "dbo.BorrowedBooksEditions",
                c => new
                    {
                        BorrowedBooks_Id = c.Int(nullable: false),
                        Edition_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.BorrowedBooks_Id, t.Edition_Id })
                .ForeignKey("dbo.BorrowedBooks", t => t.BorrowedBooks_Id, cascadeDelete: true)
                .ForeignKey("dbo.Editions", t => t.Edition_Id, cascadeDelete: true)
                .Index(t => t.BorrowedBooks_Id)
                .Index(t => t.Edition_Id);
            
            DropTable("dbo.BorrowedBooksBooks");
        }
        
        public override void Down()
        {
            CreateTable(
                "dbo.BorrowedBooksBooks",
                c => new
                    {
                        BorrowedBooks_Id = c.Int(nullable: false),
                        Book_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.BorrowedBooks_Id, t.Book_Id });
            
            DropForeignKey("dbo.BorrowedBooksEditions", "Edition_Id", "dbo.Editions");
            DropForeignKey("dbo.BorrowedBooksEditions", "BorrowedBooks_Id", "dbo.BorrowedBooks");
            DropIndex("dbo.BorrowedBooksEditions", new[] { "Edition_Id" });
            DropIndex("dbo.BorrowedBooksEditions", new[] { "BorrowedBooks_Id" });
            DropTable("dbo.BorrowedBooksEditions");
            CreateIndex("dbo.BorrowedBooksBooks", "Book_Id");
            CreateIndex("dbo.BorrowedBooksBooks", "BorrowedBooks_Id");
            AddForeignKey("dbo.BorrowedBooksBooks", "Book_Id", "dbo.Books", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BorrowedBooksBooks", "BorrowedBooks_Id", "dbo.BorrowedBooks", "Id", cascadeDelete: true);
        }
    }
}
